server:
  port: 8081
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  application:
    name: bookstoreService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/bookstore?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
    show-sql: true

jwt:
  expiration: 604800
  secret: bookstore-secret
  tokenHead: Bearer
  tokenHeader: Authorization

